- name: Kubernetes Playbook
  hosts: 127.0.0.1
  connection: local
  vars:
    service_template: "service.j2"
    controller_template: "controller.j2"
    endpoints_template: "endpoints.j2"
    secret_template: "secret.j2"
    daemonset_template: "daemonset.j2"
    deployment_template: "deployment.j2"
    configmap_template: "configmap.j2"
    dest_path: /docker
  vars_files:
    - "services.yml"
  tasks:

    # ConfigMap

    - name: configmap template
      template: src={{configmap_template}} dest={{dest_path}}/{{item.name}}-configmap.json
      with_items: "{{ configmaps }}"
      when: configmaps is defined
      no_log: True

    - name: apply configmaps
      command: kubectl --server="{{kubernetes_master}}" apply -f {{dest_path + '/' + item.name + '-configmap.json'}} --record=true
      with_items: "{{ configmaps }}"
      when: configmaps is defined
      no_log: True

    # Secrets

    - name: secret template
      template: src={{secret_template}} dest={{dest_path}}/{{item.name}}-secret.json
      with_items: "{{ secrets }}"
      when: secrets is defined
      no_log: True

    - name: apply secrets
      command: kubectl --server="{{kubernetes_master}}" apply -f {{dest_path + '/' + item.name + '-secret.json'}} --record=true
      with_items: "{{ secrets }}"
      when: secrets is defined
      no_log: True

    # DaemonSets

    - name: daemonset template
      template: src={{daemonset_template}} dest={{dest_path}}/{{item.name}}-daemonset.json
      with_items: "{{ daemonsets }}"
      when: daemonsets is defined
      no_log: True

    - name: apply daemonsets
      command: kubectl --server="{{kubernetes_master}}" apply -f {{dest_path + '/' + item.name + '-daemonset.json'}} --record=true
      with_items: "{{ daemonsets }}"
      when: daemonsets is defined
      no_log: True

    # Services

    - name: service template
      template: src={{service_template}} dest={{dest_path}}/{{item.name}}-service.json
      with_items: "{{ services }}"
      no_log: True

    - name: apply services
      command: kubectl --server="{{kubernetes_master}}" apply -f {{dest_path + '/' + item.name + '-service.json'}} --record=true
      with_items: "{{ services }}"
      no_log: True

    # Replication Controllers

    - name: controller template
      template: src={{controller_template}} dest={{dest_path}}/{{item.name}}-controller.json
      with_items: "{{ services }}"
      when: item.containers is defined and item.strategy is not defined
      no_log: True

    - name: apply controllers
      command: kubectl --server="{{kubernetes_master}}" apply -f {{dest_path + '/' + item.name + '-controller.json'}} --record=true
      with_items: "{{ services }}"
      when: item.containers is defined and item.strategy is not defined
      no_log: True

    # - name: delete other replicationControllers
    #   uri: url={{kubernetes_master}}/api/v1/namespaces/default/replicationcontrollers/{{item.metadata.name}}
    #   with_items: existing_c ontrollers.json['items']
    #   when: item.spec.selector.name not in services|map(attribute='name')
    #   no_log: True

    # Deployments

    - name: deployment template
      template: src={{deployment_template}} dest={{dest_path}}/{{item.name}}-deployment.json
      with_items: "{{ services }}"
      when: item.containers is defined and item.strategy is defined
      no_log: True

    - name: apply deployments
      command: kubectl --server="{{kubernetes_master}}" apply -f {{dest_path + '/' + item.name + '-deployment.json'}} --record=true
      with_items: "{{ services }}"
      when: item.containers is defined and item.strategy is defined
      no_log: False

    # Endpoints

    - name: endpoints template
      template: src={{endpoints_template}} dest={{dest_path}}/{{item.name}}-endpoints.json
      with_items: "{{ services }}"
      when: item.endpoints is defined
      no_log: True

    - name: apply endpoints
      command: kubectl --server="{{kubernetes_master}}" apply -f {{dest_path + '/' + item.name + '-endpoints.json'}} --record=true
      with_items: "{{ services }}"
      when: item.endpoints is defined
      no_log: True
