services:
  - name: redis-master
    ports: 
      - port: 6379
    replicas: 1
    containers:
      - name: redis-master
        image: redis:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 6379

  - name: nginx
    ports: 
      - port: 80
    replicas: 1
    containers:
      - name: nginx
        image: minux:5000/nginx
        imagePullPolicy: Always
        ports:
          - containerPort: 80

  - name: google
    ports:
      - port: 80
    endpoints:
      addresses:
        - IP: "74.125.225.7"
